
export interface User {
  id: string;
  name: string;
  email: string;
  role: 'STUDENT' | 'ADMIN' | 'FACULTY' | 'SECURITY'; // Updated to uppercase to match backend enum
  regNo?: string;
  avatar?: string;
  department?: string;
}

export interface StudentProfile {
  id: string;
  userId: string;
  dob?: string;
  phone?: string;
  address?: string;
  bio?: string;
  avatarUrl?: string;
  hostelName?: string;
  roomNumber?: string;
  wardenName?: string;
  department?: string;
  course?: string;
  semester?: number;
  user?: Partial<User>;
}

export interface MessMenuItem {
  category: 'Breakfast' | 'Lunch' | 'Dinner';
  items: string[];
  calories: number;
  protein?: number;
  carbs?: number;
  rating: number; // 1-5
  crowdLevel: number; // 0-100%
  waitTimes?: string;
  timeRange?: string;
}

export interface MailSummary {
  id: string;
  sender: string;
  subject: string;
  summary: string; // Generated by Gemini
  urgent: boolean;
  type?: 'Academic' | 'Event' | 'Lost & Found' | 'General';
  timestamp: Date;
  timeAgo?: string;
}

export interface Announcement {
  id: string;
  title: string;
  type: 'General' | 'Academic' | 'Emergency';
  content: string;
  timestamp: Date;
}

export interface ScheduleItem {
  id: string;
  subject: string;
  code: string;
  time: string;
  room: string;
}

export interface Assignment {
  id: string;
  title: string;
  dueDate: string;
  subject: string;
}

export interface NearbyHub {
  id: string;
  name: string;
  distance: string;
  tags: string[];
  rating: number;
  image?: string;
}
